// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pYM5_xXEaYhtRqzi4vpPAGhNDVEBKYA',
    appId: '1:1091271496660:android:b2ac0e04a4735ffdb53c41',
    messagingSenderId: '1091271496660',
    projectId: 'magzmotron-5ae93',
    storageBucket: 'magzmotron-5ae93.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0pYM5_xXEaYhtRqzi4vpPAGhNDVEBKYA',
    appId: '1:1091271496660:web:b2ac0e04a4735ffdb53c41',
    messagingSenderId: '1091271496660',
    projectId: 'magzmotron-5ae93',
    authDomain: 'magzmotron-5ae93.firebaseapp.com',
    storageBucket: 'magzmotron-5ae93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj5BmPDm49PduPAdQiiNw6aoksN7DaupU',
    appId: '1:1091271496660:ios:05b738dfe51a6f6cb53c41',
    messagingSenderId: '1091271496660',
    projectId: 'magzmotron-5ae93',
    storageBucket: 'magzmotron-5ae93.firebasestorage.app',
    iosBundleId: 'com.example.magzmotron',
  );
}
