// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYthovKfVp5WkDEeAqPNjNuI9a_kDhgBo',
    appId: '1:323935471456:android:baba6da1df97578388c005',
    messagingSenderId: '323935471456',
    projectId: 'phepha-mv-isdp',
    storageBucket: 'phepha-mv-isdp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2jT8OaKsPJI-mdjQqRi88kWOdT3lVKY',
    appId: '1:323935471456:web:f013f9f37010b1ee88c005',
    messagingSenderId: '323935471456',
    projectId: 'phepha-mv-isdp',
    authDomain: 'phepha-mv-isdp.firebaseapp.com',
    storageBucket: 'phepha-mv-isdp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMfDw7NsbJZocTN43fSLFmEZVTone4wSI',
    appId: '1:323935471456:ios:3285f0bc7aff8c8788c005',
    messagingSenderId: '323935471456',
    projectId: 'phepha-mv-isdp',
    storageBucket: 'phepha-mv-isdp.firebasestorage.app',
    iosBundleId: 'za.co.phephamv.isdp',
  );
}
