name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Show versions
        run: |
          flutter doctor -v
          xcodebuild -version
          swift --version

      - name: Clean project
        run: flutter clean

      - name: Get packages
        run: flutter pub get

      - name: Disable iOS signing
        run: |
          /usr/libexec/PlistBuddy -c "Set :objects:97C146ED1CF9000F007C117D:attributes:TargetAttributes:97C146ED1CF9000F007C117D:DevelopmentTeam ''" ios/Runner.xcodeproj/project.pbxproj || true
          sed -i '' 's/DEVELOPMENT_TEAM = [A-Z0-9]*;/DEVELOPMENT_TEAM = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = "Apple Development";/CODE_SIGN_IDENTITY = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "Apple Development";/"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*;/PROVISIONING_PROFILE_SPECIFIER = "";/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS app without codesign
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=CODE_SIGNING_ALLOWED=NO

      - name: Create unsigned IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          cd build/ios/ipa
          zip -r Runner-unsigned.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner-unsigned-ipa
          path: build/ios/ipa/Runner-unsigned.ipa
